configMapGenerator:
- files:
  - extra-manifest/....
  - extra-manifest/....
  name: sno-ran-du-extra-manifest-1
  namespace: sno-ran-du-v4-16
generatorOptions:
  disableNameSuffixHash: true

resources:
- sno-ran-du/ns.yaml
- sno-ran-du/sno-ran-du-v1.yaml
- sno-ran-du/clusterinstance-defaults.yaml
- sno-ran-du/policytemplates-defaults.yaml
- sno-ran-du/pull-secret.yaml
