# permissions for end users to edit orano2ims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: orano2ims-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oran-o2ims
    app.kubernetes.io/part-of: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
  name: orano2ims-editor-role
rules:
- apiGroups:
  - oran.openshift.io
  resources:
  - orano2ims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oran.openshift.io
  resources:
  - orano2ims/status
  verbs:
  - get
