apiVersion: oran.openshift.io/v1alpha1
kind: ORANO2IMS
metadata:
  labels:
    app.kubernetes.io/name: orano2ims
    app.kubernetes.io/instance: orano2ims-sample
    app.kubernetes.io/part-of: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oran-o2ims
  name: sample
  namespace: oran-o2ims
spec:
  cloudId: f7fd171f-57b5-4a17-b176-9a73bf6064a4
  ingressHost: o2ims.apps.global-hub.karmalabs.corp
  resourceServerConfig:
    enabled: false

