apiVersion: oran.openshift.io/v1alpha1
kind: ClusterTemplate
metadata:
  labels:
    app.kubernetes.io/name: clustertemplate
    app.kubernetes.io/instance: clustertemplate-sample
    app.kubernetes.io/part-of: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oran-o2ims
  name: clustertemplate-sample
spec:
  # TODO(user): Add fields here
