resources:

# Inventory:
- bases/oran.openshift.io_orano2imses.yaml

# Hardware management:
- bases/hardwaremanagement.oran.openshift.io_nodepools.yaml
- bases/hardwaremanagement.oran.openshift.io_nodes.yaml

# Provisioning:
- bases/oran.openshift.io_clustertemplates.yaml
- bases/oran.openshift.io_clusterrequests.yaml

configurations:
- kustomizeconfig.yaml
